[package]
name = "dangerous"
version = "0.1.0"
authors = ["42yeah <42yeah@gmx.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
